      - name: Apply v0lk3n NetHunter Patches
        run: |
          # Use the official GitHub Patch API links
          curl -fLO https://github.com/V0lk3n/nethunter_kernel_samsung_exynos9820/commit/8091f09c7333908f9037c28c89b47e5898851411.patch
          curl -fLO https://github.com/V0lk3n/nethunter_kernel_samsung_exynos9820/commit/53018860a4f669a4868f0577a76c8c838883592c.patch
          
          # Apply the patches to the Lineage 23.2 source
          patch -p1 --ignore-whitespace < 8091f09c7333908f9037c28c89b47e5898851411.patch
          patch -p1 --ignore-whitespace < 53018860a4f669a4868f0577a76c8c838883592c.patch
          
